on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: "Target Branch"
        required: true
        default: "master"
        # Define options for the target branch dropdown
        options:
          - master
          - release-please-update
  push:
    branches:
      - master
      - release-please-update

name: Release Please
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          command: manifest
          pull-request-header: "Homepage Release Request"
          default-branch: ${{ github.event.inputs.target-branch }}
