on:
  push:
    branches:
      - master

name: Release Please
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          command: manifest
          pull-request-header: "Homepage Release Request"
          default-branch: "master"
