on:
  workflow_dispatch:
  push:
    branches:
      - master

name: Release Please

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: release
        id: release
        uses: googleapis/release-please-action@v4
        with:
          command: manifest
          pull-request-header: "release-please release request"
          default-branch: "master"
          target-branch: "master"
